#!/usr/bin/env bash
#A bash script that displays Best School 10 times but on the 9th interation it diplays Best School the Hi on the next line

var1=10

while [ $var1 -gt 0 ]
do
 echo "Best School"
 if [ $var1 -eq 2 ]
 then
  echo "Hi"
 fi
 ((var1--))
done
