#!/usr/bin/env bash
# A bash script that loops from 1-10. It displays "bad luck" on the 4th interation, "good luck" on the 8th and "Best School" for the rest of the iteration

var1=10

while [ $var1 -gt 0 ]
do
 if [ $var1 -eq 7 ]
 then
  echo "bad luck"
 elif [ $var1 -eq 3 ]
 then
  echo "good luck"
 else
  echo "Best School"
 fi
 (( var1-- ))
done
