#!/usr/bin/env bash
#A bash script that displays the content of the current directory in a list format
# only part of the name after the first dash is displayed
# it does not display hidden files

list=$(ls)

for i in $list
do
 echo "$i" | cut -d '-' -f2
done
