#!/usr/bin/env bash
#A bash script that gives info about the school file
# The Bash script checks if the file exists
#   if the school file exist it prints "school file exists"
#   if the file does not exist it prints "school file does not exist"
# Also if the file exists it checks for:
#   if the file is empty it prints "school file is empty"
#   if the file is not empty it prints "school file is not empty"
#   if the file is a regular file it prints "school is a regular file"

if [ -e "school" ]
then
 echo "school file exists"
 if [ -s "school" ]
 then
  echo "school file is not empty"
 else
  echo "school file is empty"
 fi
 if [ -f "school" ]
 then
  echo "school is a regular file"
 fi
else
 echo "school file does not exist"
fi
